networks:
  test:
    driver: bridge
    external: true
services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: "csvserver"
    environment:
      CSVSERVER_BORDER: "Orange"
    ports:
      - '9393:9300'
    networks:
      - test
    volumes:
      - ./inputFile:/csvserver/inputdata

  prometheus:
    image: prom/prometheus:v2.22.0
    container_name: prometheus
    volumes:
      - /Users/aamitg/2021/hgbu/solution/csvserver/prometheus:/etc/prometheus
      - /Users/aamitg/2021/hgbu/solution/csvserver/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - test
    labels:
      org.label-schema.group: "monitoring"
