global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'csvserver'
    scrape_interval: 5s
    static_configs:
      - targets: ['csvserver:9300']
    
      
  - job_name: 'prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['localhost:9090']

